export const PHOTOS_NETWORK_REQUEST = 'PHOTOS_NETWORK_REQUEST';
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const ON_ERROR = 'ON_GET_PHOTOS_ERROR';
