export const SCREEN_STACK = 'Screen Stack';
export const HOME_SCREEN = 'Home Screen';
export const PROFILE_SCREEN = 'Profile Screen';
export const DISPLAY_SCREEN = 'Display Screen';
export const ABOUT_SCREEN = 'About Screen';
export const TAB_SCREEN = 'Tab Screen';
export const EXAMPLE_SCREEN = 'Example Screen';
export const SIGN_IN = 'Sign In';
export const AUTH = 'Auth';
