export const ALBUMS_NETWORK_REQUEST = 'ALBUMS_NETWORK_REQUEST';
export const GET_ALBUMS = 'GET_ALBUMS';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const ON_ERROR = 'ON_GET_ALBUMS_ERROR';
